# Generated by Django 2.1.5 on 2019-02-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='voter',
        ),
    ]
